export const SAVE_CURRENT_USER = "SAVE_CURRENT_USER";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const LOAD_ADDRESSES_SUCCESS = "LOAD_ADDRESSES_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
