import React from "react";
import "./faqComponent.css";

function FaqComponent() {
  return (
    <div className="text-content page-section">
      Is the Fake Name Generator illegal?
      <br /> The simple answer is no, the Fake Name Generator is not illegal.
      <br />
      <p>
        We do not condone, support, or encourage illegal activity of any kind.
        We will cooperate with law enforcement organizations to assist in the
        prosecution of anyone that misuses the information we provide or that
        asks us to provide illegal materials, such as forged documents or
        genuine credit card numbers.
      </p>
      <br />
      <p>
        All of the information we provide, including credit card numbers and
        national identification numbers, are fake. They can't be used to make
        purchases online or to obtain employment. We cannot and will not provide
        genuine credit card numbers or national identification numbers.
      </p>
      <br />
      <p>
        Can I use your identities in my book, on my website, in my movie, in my
        video game, etc? Absolutely! Please be sure to review the license first.
        You are required to give attribution to the Fake Name Generator for any
        information you use from our website.
      </p>
      <br />
      <p>
        What can I use the Fake Name Generator identities for?
        <br />
        Thousands of individuals, companies, and government organizations have
        found useful and creative things to do with the Fake Name Generator.
        Here are a few examples:
      </p>
      <br />
      <p>
        Quality test data can be hard to come by, especially with laws (such as
        HIPAA) preventing use of real data. Read more on the dangers of testing
        with real data.
        <br />
        Many websites, such message boards, are poorly designed, making it
        difficult for visitors from foreign countries to sign up for accounts.
        Using fake information, you can easily fill out the sign up forms and
        log in to the site.
      </p>
      Use fake information when filling out forms to avoid giving out personal
      information. <br />
      Generate a false identity to use as your pseudonym on the internet. This
      allows you to keep your real life and your internet life separate. <br />
      Get ideas for names to use for characters in a book or story. <br />
      Generated credit cards can be used to test basic client-/server-side
      validation techniques without accidently processing a real card. <br />
      Generated national identity numbers can be used to test basic
      client-/server-side validation techniques without risking disclosure of
      real information. <br />
      Where do these identities come from? <br />
      Name: Names are generated by randomly pulling a first and a last name out
      of a database. The database was compiled from public domain sources. Odds
      are that someone somewhere out of the billions of people who have lived on
      this planet has had the same name as the one generated. However, we assure
      you that these names are randomly generated.
      <br />
      <p>
        Street address: The house number is a randomly generated number. The
        street name is pulled from a database of plausible street names for the
        state/country being generated. Odds are that the generated street
        address is not valid.
      </p>
      <br />
      <p>
        City, state, and postal code: We have compiled a database containing
        hundreds of thousands of valid city, state, and postal code
        combinations. One of these combinations is randomly pulled from the
        database for each identity.
      </p>
      <br />
      <p>
        Email address: The generated email address is in the format of Generated
        Name@Anonymous Email Service.com. The anonymous email services are
        provided free of charge by the Fake Mail Generator, our temporary email
        service.
      </p>
      <br />
      <p>
        Telephone number: We have compiled a database of valid area codes and
        prefixes. One of these combinations is randomly pulled from the
        database, and then a random number of the appropriate length is added to
        the end to make the phone number the correct length.
      </p>
      <br />
      <p>
        Mother's maiden name: A random name is pulled from our database of last
        names, and listed as the "mother's maiden name".
      </p>
      <br />
      <p>Birthday: The birthday is a randomly generated date.</p>
      <br />
      <p>
        Credit card: We use Graham King's PHP credit card generator. This script
        creates a fake, but syntax valid, credit card number. The expiration
        date is randomly generated to be a date in the near future. We use
        inactive prefixes to ensure that these cards are not used for fraud.
        These credit card numbers do not reflect anyone's real credit card
        number.
      </p>
      <br />
      <p>
        National identification number: Social security numbers are generated
        using the pattern outlined by the Social Security Administration. Social
        insurance numbers are generated using the pattern outlined on Wikipedia.
        These numbers are completely random, and are extremely unlikely to match
        the generated name.
      </p>
      <br />
      <p>
        Can I get a copy of the source code to your site?
        <br />
        No. We may eventually make it open-source, but currently it is a
        closed-source, copyrighted work.
      </p>
      <br />
      <p>
        Can you add a new feature, country, or nameset?
        <br />
        Probably. Use the contact us page to let us know what you want and we'll
        see what we can do.
      </p>
      <br />
    </div>
  );
}

export default FaqComponent;
